version: "3.8"

services:
  backend:
    image: yourdockerhubid/chatbot-backend:latest
    container_name: chatbot-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    # volumes: [선택] 필요 시 추가
    #   - ./backend:/app

  frontend:
    image: yourdockerhubid/chatbot-frontend:latest
    container_name: chatbot-frontend
    restart: always
    ports:
      - "5173:5173"
