version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatbot_backend
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatbot_frontend
    ports:
      - "8505:8505"
    restart: always
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
