version: "3.8"

services:
  backend:
    image: dxorud/chatbot_backend:latest
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    image: dxorud/chatbot_frontend:latest
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    restart: unless-stopped
