apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-frontend
  template:
    metadata:
      labels:
        app: chatbot-frontend
    spec:
      containers:
        - name: chatbot-frontend
          image: dxorud/chatbot-frontend:latest
          ports:
            - containerPort: 5173
          imagePullPolicy: Always
